#%%
from langchain.agents import create_agent
from langchain.agents.middleware import TodoListMiddleware
from rich import print
from langchain.messages import HumanMessage, SystemMessage
import os
from dotenv import load_dotenv

################################ Environment Setup ################################

load_dotenv()
 
print(os.environ["LANGFUSE_PUBLIC_KEY"])
 
# Enable LangChain tracing for observability and debugging
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_PROJECT"] = os.getenv("LANGCHAIN_PROJECT", "LangChain_101")

#%%
################################ Example 1 Basics ################################

# Initialize the agent with task management capabilities
agent = create_agent(
    model="gpt-4.1-nano",
    middleware=[TodoListMiddleware()], # Inject middleware to intercept and manage to-do items
)

# Execute the agent with a natural language travel request
response = agent.invoke(
   {
        "messages": [
            HumanMessage("Plan a trip to Spain for this weekend.")
        ]
    })

print(response)

#%%
################################ Output Processing ################################

print("To-Do List:")
    
# Extract the final response message from the conversation history
print(response["messages"][-1].content)

# %%
# Display the structured to-do objects generated by the middleware
print(response["todos"])

# %%
# Access specific metadata from the first generated task
print(response["todos"][0]['content'])
print(response["todos"][0]['status'])
# %%


################################ Example 2  ################################

# Initialize the agent with task management capabilities
agent = create_agent(
    model="gpt-4.1-nano",
    middleware=[TodoListMiddleware()], # Inject middleware to intercept and manage to-do items
)

# Execute the agent with a natural language travel request
response = agent.invoke(
   {
        "messages": [
            HumanMessage("Plan a trip to Spain for this weekend.")
        ]
    })

print(response)
#%%
